FROM ruby:3.3.7-slim

# Установка необходимых зависимостей
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev git curl nodejs postgresql-client \
    imagemagick libvips-dev libjpeg-dev libwebp-dev \
    vim nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Рабочая директория
WORKDIR /rails

# Установка Bundler и настройка
RUN gem install bundler
ENV BUNDLE_PATH=/usr/local/bundle

# Копирование Gemfile и установка зависимостей
COPY Gemfile Gemfile.lock ./
RUN bundle config set without 'production' && \
    bundle install --jobs 4 --retry 3

# Копирование скрипта входа в Docker
COPY bin/docker-entrypoint /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint

# Настройка переменных окружения для разработки
ENV RAILS_ENV=development
ENV RAILS_LOG_TO_STDOUT=true
ENV LANG=C.UTF-8
ENV EDITOR=vim

# Порт для приложения
EXPOSE 3000

# Установка точки входа
ENTRYPOINT ["docker-entrypoint"]

# Команда по умолчанию
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
