---
openapi: 3.0.1
info:
  title: Tire Service API
  version: v1
  description: API для сервиса шиномонтажа. Предоставляет функциональность для управления
    клиентами, партнерами, сервисными точками, бронированиями и другими аспектами
    бизнеса.
  contact:
    name: API Support
    email: support@tire-service.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  "/api/v1/partners/{partner_id}/service_points":
    parameters:
    - name: partner_id
      in: path
      description: ID партнера
      required: true
      schema:
        type: integer
    post:
      summary: Создает сервисную точку с постами с индивидуальными расписаниями
      tags:
      - Service Points
      - Service Posts
      description: Создает новую сервисную точку с постами обслуживания, включая возможность
        настройки индивидуальных расписаний для каждого поста
      operationId: createServicePointWithCustomSchedulePosts
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Сервисная точка с постами создана успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID сервисной точки
                      name:
                        type: string
                        description: Название сервисной точки
                      service_posts:
                        type: array
                        description: Посты обслуживания
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            post_number:
                              type: integer
                            name:
                              type: string
                            has_custom_schedule:
                              type: boolean
                            working_days:
                              type: object
                            custom_hours:
                              type: object
                            working_days_list:
                              type: array
                              items:
                                type: string
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    description: Ошибки валидации
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                service_point:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Название сервисной точки
                      example: Автосервис с индивидуальными расписаниями
                    address:
                      type: string
                      description: Адрес сервисной точки
                      example: ул. Примерная, 123
                    city_id:
                      type: integer
                      description: ID города
                      example: 1
                    service_posts_attributes:
                      type: array
                      description: Посты обслуживания с возможностью индивидуальных
                        расписаний
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: Название поста
                            example: Пост экспресс-обслуживания
                          post_number:
                            type: integer
                            description: Номер поста
                            example: 1
                          slot_duration:
                            type: integer
                            description: Длительность слота в минутах
                            example: 30
                          has_custom_schedule:
                            type: boolean
                            description: Имеет ли пост индивидуальное расписание
                            example: true
                          working_days:
                            type: object
                            description: Рабочие дни недели для индивидуального расписания
                            example:
                              monday: true
                              tuesday: false
                              wednesday: true
                              thursday: true
                              friday: false
                              saturday: false
                              sunday: false
                          custom_hours:
                            type: object
                            description: Индивидуальные часы работы поста
                            properties:
                              start:
                                type: string
                                description: Время начала работы в формате HH:MM
                                example: '10:00'
                              end:
                                type: string
                                description: Время окончания работы в формате HH:MM
                                example: '19:00'
                        required:
                        - name
                        - post_number
                        - slot_duration
                  required:
                  - name
                  - address
                  - city_id
              required:
              - service_point
servers:
- url: http://localhost:8000
  description: Development server
- url: https://api.tire-service.com
  description: Production server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT токен для аутентификации. Получается через эндпоинт /api/v1/auth/login
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Сообщение об ошибке
        details:
          type: object
          description: Дополнительные детали ошибки
      required:
      - error
    ValidationError:
      type: object
      properties:
        errors:
          type: object
          description: Ошибки валидации по полям
      required:
      - errors
tags:
- name: Authentication
  description: Аутентификация и авторизация пользователей
- name: Clients
  description: Управление клиентами
- name: Partners
  description: Управление партнерами
- name: Service Points
  description: Управление сервисными точками
- name: Bookings
  description: Управление бронированиями
- name: Photos
  description: Управление фотографиями сервисных точек
- name: Catalogs
  description: Справочники и каталоги
- name: System
  description: Системные эндпоинты
