require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Use redis_cache_store in development (same as production) to ensure
  # consistent caching behavior. Falls back to memory_store when Redis
  # is not available.
  if ENV['REDIS_URL'].present?
    config.cache_store = :redis_cache_store, {
      url: ENV.fetch('REDIS_URL', 'redis://localhost:6379/1'),
      expires_in: 1.hour,
      namespace: 'tire_service_cache_dev',
      error_handler: -> (method:, returning:, exception:) {
        Rails.logger.warn("Redis cache error: #{exception.message}. Falling back gracefully.")
      }
    }
  else
    config.cache_store = :memory_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Настройка URL для Active Storage
  # Универсальная конфигурация для Docker и локальной разработки
  if ENV['DOCKER_ENV'] == 'true'
    # Docker конфигурация
    api_host = ENV.fetch("API_HOST", "api")
    api_port = ENV.fetch("API_PORT", 8000)
  else
    # Локальная конфигурация
    api_host = ENV.fetch("API_HOST", "localhost")
    api_port = ENV.fetch("API_PORT", 8000)
  end

  Rails.application.routes.default_url_options[:host] = api_host
  Rails.application.routes.default_url_options[:port] = api_port
  config.action_mailer.default_url_options = { host: api_host, port: api_port }
  config.active_storage.default_url_options = { host: api_host, port: api_port }

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Настройка Action Mailer для отправки писем
  config.action_mailer.perform_caching = false
  config.action_mailer.default_url_options = { host: ENV.fetch('HOST', 'localhost'), port: ENV.fetch('PORT', 8000) }
  
  # Настройка SMTP для отправки писем
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: ENV['SMTP_ADDRESS'],
    port: ENV['SMTP_PORT']&.to_i || 25,
    domain: ENV['SMTP_DOMAIN'],
    user_name: ENV['SMTP_USERNAME'],
    password: ENV['SMTP_PASSWORD'],
    authentication: 'plain',
    enable_starttls_auto: false
  }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Bullet — N+1 query detection
  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = false
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
    Bullet.add_footer = true
  end

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Разрешенные хосты для Docker и локальной разработки
  config.hosts += [
    "api",              # Docker service name
    "localhost",        # Локальный хост
    "127.0.0.1",       # Локальный IP
    "0.0.0.0",         # Все интерфейсы
    "tire_service_api", # Docker compose service name (если используется)
    /.*\.local/,       # Локальные домены (.local)
    /.*\.ngrok-free\.app/  # ngrok домены для Telegram webhook
  ]
end
